# This file is for validation and tests of code submitted to this repository.
# Created by Deivid Vale on Tue 28 May 2024

# Important information:
# We use the following external GitHub actions in this file. Their respective documentation is listed below.

# List of GitHub actions used:
# - actions/checkout@v4
#   - documentation: https://github.com/actions/checkout
# - actions/setup-java@v4
#   - documentation: https://github.com/actions/setup-java
# - actions/setup-gradle
#   - documentation: https://github.com/gradle/actions/tree/main/setup-gradle
# - actions/dependency-submission
#   - documentation: https://github.com/gradle/actions/tree/main/dependency-submission

name: Java-21 CI Build&Test with Gradle

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Clean previous build cache
        run: ./gradlew clean
      - name: Build with Gradle Wrapper
        run: ./gradlew build --rerun-tasks
